### ISSUE TITLE
Send and receive: If the transaction isn’t fulfilled, maybe add a notification that a transaction is pending.

### ISSUE THREAD

**Issue by Doneyy** [theQRL/mobile-wallet#25]
- On the page “send and receive”. After I sent the transaction, the amount on my app stays the same.  It's unclear if sending the transaction has sucseeded and is in progress. If the transaction isn’t fulfilled, but confirmed by a user on the app, would be better to have something that indicates that a transaction of .. amount is pending.
Ipad version ME279NF/A
iOS Version 12.1.1 (16C50)

**Comment by ademcan** [comment]
This issue is now solved. After a transaction is sent, the user is redirected to the main page of the app (tx history) and the "pending" transaction is visible in the list.

![simulator screen shot - iphone x - 2019-01-19 at 15 58 55](https://user-images.githubusercontent.com/1199588/51428385-5353ef00-1c03-11e9-904a-cc5ab2b1bf41.png)
