### ISSUE TITLE
The option to Open existing wallet is kind of hidden. 

### ISSUE THREAD

**Issue by Doneyy** [theQRL/mobile-wallet#29]
- On the page "Create new wallet”. The option to Open existing wallet is kind of hidden. Would not expect that in advanced options. 
Ipad version ME279NF/A
iOS Version 12.1.1 (16C50)

**Comment by ademcan** [comment]
Hi Doneyy, thank you for your comment.
This issue is now solved, see https://github.com/theQRL/mobile-wallet/pull/32 that brings the following change:
- Add "Create advanced wallet" and "Import existing wallet" options to the main create wallet screen

This is how the main view looks like now:
![simulator screen shot - iphone x - 2019-01-10 at 09 56 59](https://user-images.githubusercontent.com/1199588/50957598-e633b180-14be-11e9-96e9-aea5d5bc4942.png)
